import Head from 'next/head'
import styles from '@/styles/Home.module.css'
import Featured from '@/components/Featured'
import CoffeList from '@/components/CoffeList'

export default function Home() {
  return (
    <>
      <div className={styles.container}>
        <Head>
          <title>Beli Kopi</title>
          <meta name="description" content="Generated by create next app" />
          <meta name="viewport" content="Base coffe shop in indonesia" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <Featured/>
        <CoffeList />
      </div>
    </>
  )
}
